EnterpriseDataPipeline/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EnterpriseDataPipeline.Models;
using DynamicMVC.UI.Controllers;
using System.Threading.Tasks;

using System.Collections;
using System.Text;
using System.Web.Routing;
using DynamicMVC.Business.Attributes;
using DynamicMVC.Business.Models;
using DynamicMVC.Data;
using DynamicMVC.UI.Extensions;
using DynamicMVC.UI.ViewModels;

using DynamicMVC.UI;

using System.Data.Common;

using SSHWrapper;

using MySql.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using System.Text.RegularExpressions;

using Npgsql;

using System.Data;
using System.Data.Odbc;

using Renci.SshNet;
using System.Net.Http;
using System.IO;

using EnterpriseDataPipeline.ViewModel;
using System.Collections.ObjectModel;

namespace EnterpriseDataPipeline.Controllers
{
    //[Authorize(Roles = "Admin")]
    [Authorize(Roles = "Operator, Admin")]
    //[HandleError]
    public class JobController : Controller
    //public class JobController : DynamicController
    {
        //static ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            StorageViewModel viewModelStorage = new StorageViewModel();

            try
            {
                ApplicationDbContext db = new ApplicationDbContext();
                List<Storage> listStorage = db.Storage.OrderBy(s => s.Name).ToList();

                //var directors = new List<Storage>
                //{
                //    new Storage {Id = 1, Name = "MySQL"},
                //    new Storage {Id = 2, Name = "Hive"},
                //    new Storage {Id = 3, Name = "HBase"}
                //};
                //var selectList = new SelectList(directors, "Id", "Name");
                //var vm = new StorageViewModel { Source = selectList, SourceId = 3 };
                //return View(vm);


                var selectList = new SelectList(listStorage, "Id", "Name");
                var vm = new StorageViewModel
                {
                    Storage = selectList,
                    SourceId = 1,           //Default Source
                    DestinationId = 6       //Default Destination
                };
                return View(vm);


                //viewModelStorage.SourceList = new List<System.Web.Mvc.SelectListItem>();
                //viewModelStorage.DestinationList = new List<System.Web.Mvc.SelectListItem>();

                //viewModelStorage.SelectedSourceStorage = "MySQL";
                //viewModelStorage.SelectedDestinationStorage = "HDFS";

                //for (int i = 0; i < listStorage.Count; i++)
                //{
                //    SelectListItem selectListItem = new SelectListItem { Value = "" + listStorage[i].Id, Text ="" + listStorage[i].Name, Selected = (listStorage[i].Name == viewModelStorage.SelectedSourceStorage? true : false) };
                //    viewModelStorage.SourceList.Add(selectListItem);
                //}
                //for (int i = 0; i < listStorage.Count; i++)
                //{
                //    SelectListItem selectListItem = new SelectListItem { Value = "" + listStorage[i].Id, Text = "" + listStorage[i].Name, Selected = (listStorage[i].Name == viewModelStorage.SelectedDestinationStorage? true : false) };
                //    viewModelStorage.DestinationList.Add(selectListItem);
                //}

                //ViewBag.SourceList = viewModelStorage.SourceList;
                //ViewBag.Source = "MySQL";
                //ViewBag.DestinationList = viewModelStorage.DestinationList;

                ////return View(db.Storage.OrderBy(s => s.Name).ToList());
                //return View(viewModelStorage);
            }
            catch (Exception ex)
            {
                string str = ex.Message;
                return View("Error");
            }

            //return View();

            //ApplicationDbContext db = new ApplicationDbContext();
            //return View(db.Storage.OrderBy(s => s.Name).ToList());
        }

        #region "Get Database"
        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult GetDB(string storage)
        //public JsonResult GetDB(string storage)
        {
            JsonResult jsonResult = new JsonResult();
            string myConnectionString = "";

            try
            {
                ApplicationDbContext db = new ApplicationDbContext();
                //var tbStorage = db.Storage.Where(s => s.Name == storage).ToList();
                //var tbStorage = db.Storage.First(t => t.Name.Equals(storage, System.StringComparison.InvariantCultureIgnoreCase));
                int storageId = int.Parse(storage);
                var tbStorage = db.Storage.Where(s => s.Id == storageId).ToList(); 
                string strStorageType = tbStorage[0].Type;

                //myConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                //jsonResult = GetStorageType(myConnectionString, storage);

                //switch (storage)
                switch (strStorageType)
                {
                    case "MySQL":
                        myConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnectionMySQL"].ConnectionString;
                        myConnectionString = myConnectionString.Replace("HOST_IP", tbStorage.ToList()[0].IPAddress);
                        myConnectionString = myConnectionString.Replace("DATABASE", tbStorage.ToList()[0].DBName);
                        myConnectionString = myConnectionString.Replace("PORT_NO", tbStorage.ToList()[0].Port);
                        myConnectionString = myConnectionString.Replace("USER_ID", tbStorage.ToList()[0].UserName);
                        myConnectionString = myConnectionString.Replace("PASSWORD", tbStorage.ToList()[0].Password);
                        jsonResult = GetMySQLDB(myConnectionString, tbStorage[0].Id);
                        break;
                    case "Hive":
                        myConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnectionHive"].ConnectionString;
                        myConnectionString = myConnectionString.Replace("HOST_IP", tbStorage.ToList()[0].IPAddress);
                        myConnectionString = myConnectionString.Replace("DATABASE", tbStorage.ToList()[0].DBName);
                        myConnectionString = myConnectionString.Replace("PORT_NO", tbStorage.ToList()[0].Port);
                        myConnectionString = myConnectionString.Replace("USER_ID", tbStorage.ToList()[0].UserName);
                        myConnectionString = myConnectionString.Replace("PASSWORD", tbStorage.ToList()[0].Password);
                        jsonResult = GetHiveDB(myConnectionString, tbStorage[0].Id);
                        break;
                    case "HBase":
                        myConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnectionHBase"].ConnectionString;
                        myConnectionString = myConnectionString.Replace("HOST_IP", tbStorage.ToList()[0].IPAddress);
                        myConnectionString = myConnectionString.Replace("DATABASE", tbStorage.ToList()[0].DBName);
                        myConnectionString = myConnectionString.Replace("PORT_NO", tbStorage.ToList()[0].Port);
                        myConnectionString = myConnectionString.Replace("USER_ID", tbStorage.ToList()[0].UserName);
                        myConnectionString = myConnectionString.Replace("PASSWORD", tbStorage.ToList()[0].Password);
                        jsonResult = GetHBaseDB2(myConnectionString, storage);
                        break;
                    case "Postgres":
                        myConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnectionPostgreSQL"].ConnectionString;
                        myConnectionString = myConnectionString.Replace("HOST_IP", tbStorage.ToList()[0].IPAddress);
                        myConnectionString = myConnectionString.Replace("DATABASE", tbStorage.ToList()[0].DBName);
                        myConnectionString = myConnectionString.Replace("PORT_NO", tbStorage.ToList()[0].Port);
                        myConnectionString = myConnectionString.Replace("USER_ID", tbStorage.ToList()[0].UserName);
                        myConnectionString = myConnectionString.Replace("PASSWORD", tbStorage.ToList()[0].Password);
                        jsonResult = GetPostgresDB(myConnectionString, tbStorage[0].Id);
                        break;
                    default:
                        break;
                }
            }
            catch (Exception ex)
            {
                string strError = ex.Message;
                jsonResult = new JsonResult()
                {
                    Data = new { success = false, val = strError },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }

            return jsonResult;
        }
        private JsonResult GetMySQLDB(string myConnectionString, int storageId)
        {
            JsonResult jsonResult = new JsonResult()
            {
                Data = new { success = false, val = "" },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

            try
            {
                ApplicationDbContext db = new ApplicationDbContext();
                //var tbStorage = db.Storage.Where(s => s.Name == strStorage);

                //myConnectionString = myConnectionString.Replace("HOST_IP", tbStorage.ToList()[0].IPAddress);
                //myConnectionString = myConnectionString.Replace("DATABASE", tbStorage.ToList()[0].DBName);
                //myConnectionString = myConnectionString.Replace("PORT_NO", tbStorage.ToList()[0].Port);
                //myConnectionString = myConnectionString.Replace("USER_ID", tbStorage.ToList()[0].UserName);

EnterpriseDataPipeline/Views/DashBoard - bak2/RunJob.cshtml
@using EnterpriseDataPipeline.Models
@using System.Web.UI.WebControls; 
@model IEnumerable<object[]>
@{
    ViewBag.Title = "SV4U Enterprise Data PipeLine";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Index", "Job", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {

                <h4>Select a job to run.</h4>
                <hr />                
                <table align="center" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
				<tbody>
					<tr>
						<td style="width: 20%; text-align: center;">
							<label>Source</label>
						</td>
						<td style="width: 20%; text-align: center;">
							<label>Action</label>
						</td>						
						<td style="width: 20%; text-align: center;">
							<label>Destination</label>
						</td>						
					</tr>
					<tr>
						<td style="width: 20%; text-align: center;">
							<div class="form-group">								
                                    @{var source = new List<ListItem>
									    {
										      new ListItem { Text = "HDFS", Value="HDFS" },
										      new ListItem { Text = "Hive", Value="Hive" },
										      new ListItem { Text = "MySQL", Value="MySQL" },
										      new ListItem { Text = "Oracle", Value="Oracle" },
										      new ListItem { Text = "AWS", Value="AWS" },
										      new ListItem { Text = "MogoDB", Value="MogoDB" }
									    };
                                    }
                                    @Html.DropDownList("MySQL", new SelectList(source, "Value", "Text"), "Please Select Source")
									
							</div> 
						</td>
						<td style="width: 20%; text-align: center;">
							<input type="submit" value="Transfer >>" class="btn btn-default" />
						</td>					
						<td style="width: 20%; text-align: center;">
							<div class="form-group">								
								@{var listItemsHDFS = new List<ListItem>
									{
										  new ListItem { Text = "HDFS", Value="HDFS" },
										  new ListItem { Text = "Hive", Value="Hive" },
										  new ListItem { Text = "MySQL", Value="MySQL" },
										  new ListItem { Text = "Oracle", Value="Oracle" },
										  new ListItem { Text = "AWS", Value="AWS" },
										  new ListItem { Text = "MogoDB", Value="MogoDB" }
									};
								}
								@Html.DropDownList("HDFS",new SelectList(listItemsHDFS,"Value","Text"))
							</div>	
						</td>
					</tr>
				  </tbody>
				</table>             
            }

        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}