EnterpriseDataPipeline/Controllers/KafkaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EnterpriseDataPipeline.Models;
using DynamicMVC.UI.Controllers;
using System.Threading.Tasks;

using System.Collections;
using System.Text;
using System.Web.Routing;
using DynamicMVC.Business.Attributes;
using DynamicMVC.Business.Models;
using DynamicMVC.Data;
using DynamicMVC.UI.Extensions;
using DynamicMVC.UI.ViewModels;
using DynamicMVC.UI;

using SSHWrapper;

using MySql.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using System.Text.RegularExpressions;

using System.Data;
using System.Data.Odbc;
using System.Data.Common;
using System.Dynamic;

using Renci.SshNet;
using System.Net.Http;
using System.IO;

using EnterpriseDataPipeline.ViewModel;


namespace EnterpriseDataPipeline.Controllers
{
    [Authorize(Roles = "Installer, Admin")]
    //[HandleError]
    public class KafkaController : Controller    
    {
        //static ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            try
            {
                ApplicationDbContext db = new ApplicationDbContext();
                //return View(db.ModuleTB.OrderBy(s => s.Name).ToList());

                ViewModelModuleVM vm = new ViewModelModuleVM();
                //vm.allModuleTB = db.ModuleTB.OrderBy(s => s.Name).ToList();
                //vm.allModuleServer = db.ModuleServer.OrderBy(s => s.Name).ToList(); 
                //vm.allKafkaServer = db.KafkaServer.OrderBy(s => s.Name).ToList();
                vm.allKafkaTopics = db.KafkaTopics.OrderBy(s => s.Topics).ToList();

                return View(vm);
            }
            catch (Exception ex)
            {
                string str = ex.Message;
                return View("Error");
            }

            //return View();
        }

        private static IEnumerable<object[]> Read(DbDataReader reader)
        {
            while (reader.Read())
            {
                var values = new List<object>();
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    values.Add(reader.GetValue(i));
                }
                yield return values.ToArray();
            }
        }

        public ActionResult StartKafkaProducer(string module, string destinationServerIP)
        {
            JsonResult jsonResult = new JsonResult()
            {
                Data = new { success = false, val = "" },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            string result = "";
            string key = Guid.NewGuid().ToString();
            string strInstallationState = "Start Kafka Producer Failed";

            try
            {

                string strPuppetServerIP = "";
                string strPuppetServerName = "";
                string strPuppetServerPassword = "";
                string strPuppetServerPEM = "";
                string strJobLocation = "";


                ApplicationDbContext db = new ApplicationDbContext();

                //Find Kafka Server Parameters
                var sPuppetServerParameters = db.KafkaServer;
                strPuppetServerIP = sPuppetServerParameters.ToList()[0].IPAddress;
                strPuppetServerName = sPuppetServerParameters.ToList()[0].UserName;
                strPuppetServerPassword = sPuppetServerParameters.ToList()[0].Password;
                strPuppetServerPEM = sPuppetServerParameters.ToList()[0].PemFile;
                strJobLocation = sPuppetServerParameters.ToList()[0].JobLocation;


                //string strCmd = "python <job_location> -e <private-ec2-server-name> -i <private-ec2-ip> -u <user-name> -p <password> -k <packages>";
                //string strCmd = "<job_location>/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic <TOPIC>";

                //string strCmd = "cd <JOB_LOCATION> ; <JOB_LOCATION>/bin/connect-standalone.sh <JOB_LOCATION>/config/connect-standalone.properties <JOB_LOCATION>/config/connect-file-source.properties <JOB_LOCATION>/config/connect-file-sink.properties";
                //string strCmd = "cd <JOB_LOCATION>; nohup bin/connect-standalone.sh config/connect-standalone.properties config/connect-file-source.properties config/connect-file-sink.properties &; '\x0d'";
                //string strCmd = "cd <JOB_LOCATION>; nohup bin/connect-standalone.sh config/connect-standalone.properties config/connect-file-source.properties config/connect-file-sink.properties &; '\x0d'";
                string strCmd = "cd <JOB_LOCATION>; bin/connect-standalone.sh config/connect-standalone.properties config/connect-file-source.properties config/connect-file-sink.properties";


                //strCmd = strCmd.Replace("<private-ec2-server-name>", strDestinationServerIP).Replace("<user-name>", strDestinationServerUserName).Replace("<password>", strDestinationServerPassword);
                strCmd = strCmd.Replace("<JOB_LOCATION>", strJobLocation);
                //strCmd = strCmd.Replace("<TOPIC>", destinationServerIP);
                //strCmd = strCmd.Replace("<private-ec2-server-name>", strDestinationServerName).Replace("<private-ec2-ip>", strDestinationServerPrivateIP).Replace("<user-name>", strDestinationServerUserName).Replace("<password>", strDestinationServerPassword);
                //strCmd = strCmd.Replace("<packages>", strPackage);


                //var keyFiles = new[] { keyFile };
                var username = strPuppetServerName;

                var methods = new List<AuthenticationMethod>();
                methods.Add(new PasswordAuthenticationMethod(username, strPuppetServerPassword));
                //methods.Add(new PrivateKeyAuthenticationMethod(username, keyFiles));

                //var con = new ConnectionInfo(strPuppetServerIP, 22, strPuppetServerName, methods.ToArray());


                //var privKey = new PrivateKeyFile(strFileName);
                //ConnectionInfo connectionInfo = new PrivateKeyConnectionInfo(strPuppetServerIP, strPuppetServerName, keyFile);

                var connectionInfo = new ConnectionInfo(strPuppetServerIP, 22, strPuppetServerName, methods.ToArray()) { Timeout = new TimeSpan(0, 0, 0, 30) }; 

                //connectionInfo.Timeout = TimeSpan.

                //ConnectionInfo connectionInfo = new PasswordConnectionInfo(strPuppetServerIP, strPuppetServerName, strPuppetServerPassword);

                //ConnectionInfo connectionInfo = new PasswordConnectionInfo(strPuppetServerIP, strPuppetServerName, strPuppetServerPassword);


                using (SshClient client = new SshClient(connectionInfo))
                {
                    if (!client.IsConnected)
                        client.Connect();

                    if (client.IsConnected)
                    {
                        IDictionary<Renci.SshNet.Common.TerminalModes, uint> termkvp = new Dictionary<Renci.SshNet.Common.TerminalModes, uint>();
                        termkvp.Add(Renci.SshNet.Common.TerminalModes.ECHO, 53);

                        ShellStream shellStream = client.CreateShellStream("xterm", 80, 24, 800, 600, 1024, termkvp);

                        //shellStream.ReadTimeout = 300000;   //Read Timeout = 300 sec

                        //string strRegex = "(\\[USER@\\S*\\s*\\S*\\]$)";
                        string strRegex = "(\\[USER@\\S*\\s*~\\][#|$])";
                        //string strRegex = "([\\s*\\S*]*\\[USER@\\S*\\s*\\S*\\]#)";
                        strRegex = strRegex.Replace("USER", strPuppetServerName);

                        result = shellStream.Expect(new Regex(@strRegex)); //expect user prompt 

                        //send command
                        shellStream.WriteLine(strCmd);
                        shellStream.Flush();
                        result = shellStream.Expect(new Regex(@strRegex)); //expect user prompt

                        //shellStream.Flush();
                        result = result.Replace("<", "'<'");

                        //string strCmdConfigMySQL = "sudo sed -i -e 's/\\(bind-address = \\).*/\\$(VARIABLE)/‘ /etc/my.cnf.d/server.cnf";
                        //string strCmdConfigMySQL = "sudo sed -i -e 's/\\(bind-address = \\).*/\\$(VARIABLE)/'  /etc/my.cnf.d/server.cnf";

                        //strCmdConfigMySQL = strCmdConfigMySQL.Replace("$(VARIABLE)", "1172.31.41.128");
                        //shellStream.WriteLine(strCmdConfigMySQL);
                        //shellStream.Flush();
                        //string strTmpByte = shellStream.Expect(new Regex(@strRegex)); //expect user prompt
                        //result = result + "\n" + strTmpByte;
                        //result = result.Replace("<", "'<'");


                        //string strRegex2 = "(\\d*)\\s*\\d*\\s*/hbase/data/default/TABLE_NAME\\b";
                        //strRegex2 = strRegex2.Replace("TABLE_NAME", dbSourceTable.ToLower());
                        //Regex regex = new Regex(@strRegex2);
                        //if (regex.IsMatch(strTmpByte))
                        //{
                        //    Match match = regex.Match(strTmpByte);
                        //    string strByte = match.Groups[1].ToString();
                        //    long myByte = long.Parse(strByte) * 2;
                        //    //strTmpResult = strTmpResult.Replace("0", myByte.ToString());
                        //}

                        jsonResult = new JsonResult()
                        {
                            Data = new { success = true, val = result },
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };

                        //string strRegex2 = "(error|Error):\\s\\[Errno\\s\\S*\\]";
                        string strRegex2 = "\\[Errno\\s\\S*\\]";
                        Regex regex = new Regex(@strRegex2);
                        if (!regex.IsMatch(result))

EnterpriseDataPipeline/Views/Kafka/Index.cshtml
@using System.Dynamic;
@using EnterpriseDataPipeline.Models;
@using System.Web.UI.WebControls;
@*@model IEnumerable<EnterpriseDataPipeline.Models.ModuleTB>*@

@model EnterpriseDataPipeline.ViewModel.ViewModelModuleVM

@{
    ViewBag.Title = "SV4U Enterprise Data PipeLine - Module Installation";
}


<script>

    $(document).ready(function () {
        $("body").css("background-color", "#F3F3F3")

        //$("select").removeAttr("multiple");

        //debugger;   //Added by Anthony Lai to debug javascript; must be removed after debug is done

        //****************************************************************************************
        //btLoadMessage
        $("#btStartKafkaProducer").bind("click", function () {

            //debugger;

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            $("#taMessageLog").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            //debugger;

            var url = "@Url.Action("StartKafkaProducer", "Kafka")";
            $.get(url, {
                module: strModuleSel,
                destinationServerIP: $("#ddlKafkaServerIP").val()
            },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        $("#taMessageLog").append(data.val);
                    }
                    else
                    {
                    }
                });
        });
        //****************************************************************************************



        //****************************************************************************************
        //btLoadMessage
        $("#btStartKafkaConsumer").bind("click", function () {

            //debugger;

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            $("#taMessageLog").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            //debugger;

            var url = "@Url.Action("StartKafkaConsumer", "Kafka")";
            $.get(url, {
                module: strModuleSel,
                destinationServerIP: $("#ddlKafkaServerIP").val()
            },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        $("#taMessageLog").append(data.val);
                    }
                    else
                    {
                    }
                });
        });
        //****************************************************************************************



        //****************************************************************************************
        //btLoadMessage
        $("#btSendMessage").bind("click", function () {

            //debugger;

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            //$("#taMessageLog").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            //debugger;

            var url = "@Url.Action("SendMessage", "Kafka")";
            $.get(url, {
                module: strModuleSel,
                destinationServerIP: $("#ddlKafkaServerIP").val(),
                message: $("#taMessageLog").val(),
            },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        //$("#taMessageLog").append(data.val);
                    }
                    else
                    {
                    }
                });
        });
        //****************************************************************************************



        //****************************************************************************************
        //btLoadMessage
        $("#btLoadMessage").bind("click", function () {

            //debugger;

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            $("#taMessageLog").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            //debugger;

            var url = "@Url.Action("RunLoadMessage", "Kafka")";
            $.get(url, {
                    module: strModuleSel,
                    destinationServerIP: $("#ddlKafkaServerIP").val()
                },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        $("#taMessageLog").append(data.val);
                    }
                    else
                    {
                    }
                });

            //$("#btDisplayMessage").trigger("change");

        });
        //****************************************************************************************



        //****************************************************************************************
        //btDisplayMessage
        $("#btDisplayMessage").on("click", function () {

            //debugger;
            //Disable your cache prior to your AJAX Request
            $.ajaxSetup({ cache: false });

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            $("#taDisplayMessageResult").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            var url = "@Url.Action("RunDisplayMessage", "Kafka")";
            $.get(url, {
                module: strModuleSel,
                destinationServerIP: $("#ddlKafkaServerIP").val()
            },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        $("#taDisplayMessageResult").empty();
                        $("#taDisplayMessageResult").append(data.val);
                    }
                    else
                    {
                    }
                });
        });
        //****************************************************************************************

    });

</script>


<h2>
    @ViewBag.Title.
</h2>

<div class="row">
    <div class="col-md-8">   
            <h4>Kafka High-throughput Distributed Messaging.</h4>
            <br />
            @*Source Query*@
            <table align="left" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
                <tbody>
                    <tr>
                        @*<td style="width: 20%; text-align: center;">
                            <label>Module:</label>
                        </td>*@
                        <td style="width: 20%; text-align: center;">
                            <label>Kafka Topics</label>
                        </td>
                        <td style="width: 20%; text-align: center;">
                            <label>Producer Action</label>
                        </td>
                        <td style="width: 20%; text-align: center;">
                            <label>Consumer Action</label>
                        </td>
                        <td style="width: 20%; text-align: center;">
                            <label>Message Action</label>
                        </td>
                    </tr>
                    <tr>
                        @*<td style="width: 20%; text-align: center;" valign="middle">
                            @if (Model != null)
                            {
                                @Html.ListBox("Module", new SelectList(Model.allModuleTB.Select(i => i.Name).Distinct().ToList(), "Mysql"), new { @class = "width305", @id = "lbModule", size = 5, style = "height: 180px; width:auto;" })
                            }
                        </td>*@
                        <td style="width: 20%; text-align: center;" valign="middle">
                            @*@{var mItemsTB = new List<SelectListItem> {
                                    new SelectListItem { Text = "198.89.115.49", Value = "198.89.115.49"},
                                    new SelectListItem { Text = "198.89.115.123", Value = "198.89.115.123"} };}
                            @Html.DropDownList("DestinationServerIP", new SelectList(mItemsTB, "Value", "Text", mItemsTB.ToString()), new { @class = "width305", @id = "ddlDestinationServerIP", size = 1, style = "width:auto" })*@
                            @if (Model != null)
                            {
                                @Html.DropDownList("KafkaServerIP", new SelectList(Model.allKafkaTopics.Select(i => i.Topics).Distinct().ToList(), "198.89.115.123"), new { @class = "width305", @id = "ddlKafkaServerIP", size = 1, style = "width:auto" })
                            }
                        </td>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            <input id="btStartKafkaProducer" type="submit" value="Start Producer" class="btn btn-default" />
                        </td>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            <input id="btStartKafkaConsumer" type="submit" value="Start Consumer" class="btn btn-default" />
                        </td>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            <input id="btDisplayMessage" type="submit" value="Display Message" class="btn btn-default" />
                        </td>
                    </tr>
                </tbody>
            </table>  
            <br />
            <br />      
        </div>
</div>

<div>
    <table align="left" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
        <tbody>
            <tr>
                <td>
                    <label>Message:</label>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextArea("LoadMessageLog", null, new { @class = "form-control-SV4U-TextArea", @id = "taMessageLog", @cols = "250", @style = "height: 200px; width: 600px;" })
                </td>
                <td></td>
            </tr>
            <tr>
                <td style="width: 20%; text-align: center;" valign="middle">
                    <input id="btSendMessage" type="submit" value="Send Message" class="btn btn-default" />
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div>
    <table align="left" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
        <tbody>
            <tr>
                <td>
                    <label>Message in Queue:</label>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextArea("DisplayMessageResult", null, new { @class = "form-control-SV4U-TextArea", @id = "taDisplayMessageResult", @cols = "250", @style = "height: 200px; width: 600px;" })
                </td>
            </tr>
        </tbody>
    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}