EnterpriseDataPipeline/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EnterpriseDataPipeline.Models;
using DynamicMVC.UI.Controllers;
using System.Threading.Tasks;

using System.Collections;
using System.Text;
using System.Web.Routing;
using DynamicMVC.Business.Attributes;
using DynamicMVC.Business.Models;
using DynamicMVC.Data;
using DynamicMVC.UI.Extensions;
using DynamicMVC.UI.ViewModels;
using DynamicMVC.UI;

using SSHWrapper;

using MySql.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using System.Text.RegularExpressions;

using System.Data;
using System.Data.Odbc;
using System.Data.Common;
using System.Dynamic;

using Renci.SshNet;
using System.Net.Http;
using System.IO;

using EnterpriseDataPipeline.ViewModel;


namespace EnterpriseDataPipeline.Controllers
{
    [Authorize(Roles = "Installer, Admin")]
    //[HandleError]
    public class ModuleController : Controller    
    {
        //static ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            try
            {
                ApplicationDbContext db = new ApplicationDbContext();
                //return View(db.ModuleTB.OrderBy(s => s.Name).ToList());

                ViewModelModuleVM vm = new ViewModelModuleVM();
                vm.allModuleTB = db.ModuleTB.OrderBy(s => s.Name).ToList();
                vm.allModuleServer = db.ModuleServer.OrderBy(s => s.Name).ToList(); 
                //vm.allModuleTB = db.ModuleTB.ToList();
                //vm.allModuleServer = db.ModuleServer.ToList(); 

                return View(vm);
            }
            catch (Exception ex)
            {
                string str = ex.Message;
                return View("Error");
            }

            //return View();
        }

        private static IEnumerable<object[]> Read(DbDataReader reader)
        {
            while (reader.Read())
            {
                var values = new List<object>();
                for (int i = 0; i < reader.FieldCount; i++)
                {
                    values.Add(reader.GetValue(i));
                }
                yield return values.ToArray();
            }
        }

        public ActionResult RunInstallation(string module, string destinationServerIP)        
        {
            JsonResult jsonResult = new JsonResult()
            {
                Data = new { success = false, val = "" },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            string result = "";
            string key = Guid.NewGuid().ToString();
            string strInstallationState = "Installation Failed";

            try
            {

                string strPuppetServerIP = "";
                string strPuppetServerName = "";
                string strPuppetServerPassword = "";
                string strPuppetServerPEM = "";
                string strJobLocation = "";

                string strDestinationServerIP = "";
                string strDestinationServerPrivateIP = "";
                string strDestinationServerName = "";
                string strDestinationServerUserName = "";
                string strDestinationServerPassword = "";
                module = module.Remove(module.Length-1);
                string[] str = module.Split(',');
                string strPackage = "";

                if (str.Length == 1)
                {
                    strPackage += str[0];
                    strPackage = strPackage.ToLower();
                }
                else
                {
                    strPackage = "<";
                    for (int i = 0; i < str.Length; i++)
                    {
                        strPackage += str[i] + ":";
                    }

                    strPackage = strPackage.Remove(strPackage.Length - 1);
                    strPackage = strPackage.ToLower() + ">";

                    if(!strPackage.Contains(","))
                    {
                       strPackage = strPackage.Replace("<", "").Replace(">", "");
                    }
                }

                //special handling for MySQL server installation
                strPackage = strPackage.Replace("mysql", "'::mysql::server'");

                ApplicationDbContext db = new ApplicationDbContext();

                //Find Puppet Server Parameters
                var sPuppetServerParameters = db.PuppetServer;
                strPuppetServerIP = sPuppetServerParameters.ToList()[0].IPAddress;
                strPuppetServerName = sPuppetServerParameters.ToList()[0].UserName;
                strPuppetServerPassword = sPuppetServerParameters.ToList()[0].Password;
                strPuppetServerPEM = sPuppetServerParameters.ToList()[0].PemFile;
                strJobLocation = sPuppetServerParameters.ToList()[0].JobLocation;

                //Find ModuleServer Parameters
                var sClusterParameters = db.ModuleServer.Where(i => i.IPAddress == destinationServerIP);
                strDestinationServerPrivateIP = sClusterParameters.ToList()[0].PrivateIPAddress;
                strDestinationServerIP = sClusterParameters.ToList()[0].IPAddress;
                strDestinationServerName = sClusterParameters.ToList()[0].Name;
                strDestinationServerUserName = sClusterParameters.ToList()[0].UserName;
                strDestinationServerPassword = sClusterParameters.ToList()[0].Password;

                //string strCmd = "python /root/prasanna-work/connect-host.py -host <hostname> -user <user-name> -pass <password> -packages <packages>";
                //string strCmd = "python /tmp/MyAutomation/ssh.py -e <private-ec2-server-name> -u <user-name> -p <password> -k <packages>";
                //string strCmd = "python /tmp/MyAutomation/ssh.py -e <private-ec2-server-name> -i <private-ec2-ip> -u <user-name> -p <password> -k <packages>";

                string strCmd = "python <job_location> -e <private-ec2-server-name> -i <private-ec2-ip> -u <user-name> -p <password> -k <packages>";

                //strCmd = strCmd.Replace("<private-ec2-server-name>", strDestinationServerIP).Replace("<user-name>", strDestinationServerUserName).Replace("<password>", strDestinationServerPassword);
                strCmd = strCmd.Replace("<job_location>", strJobLocation);
                strCmd = strCmd.Replace("<private-ec2-server-name>", strDestinationServerName).Replace("<private-ec2-ip>", strDestinationServerPrivateIP).Replace("<user-name>", strDestinationServerUserName).Replace("<password>", strDestinationServerPassword);
                strCmd = strCmd.Replace("<packages>", strPackage);

                //string key = Guid.NewGuid().ToString();
                //DoCreateJobStatus(key, strDestinationServerName, strDestinationServerIP, strPackage, db);
                DoCreateJobStatus(key, strDestinationServerName, strDestinationServerIP, module, db);

                //ConnectionInfo connectionInfo = new PasswordConnectionInfo(strPuppetServerIP, strPuppetServerName, strPuppetServerPassword);

                //var privKey = new PrivateKeyFile(new MemoryStream(Encoding.ASCII.GetBytes(sshPrivateKeyString)));
                //string strFileName = "";
                //var path = Server.MapPath(@"~/SSHKey/sv4u.pem");

                var path = Server.MapPath(@"~/SSHKey/" + strPuppetServerPEM);
                var keyFile = new PrivateKeyFile(path);

                var keyFiles = new[] { keyFile };
                var username = strPuppetServerName;

                var methods = new List<AuthenticationMethod>();
                methods.Add(new PasswordAuthenticationMethod(username, strPuppetServerPassword));
                methods.Add(new PrivateKeyAuthenticationMethod(username, keyFiles));

                //var con = new ConnectionInfo(strPuppetServerIP, 22, strPuppetServerName, methods.ToArray());


                //var privKey = new PrivateKeyFile(strFileName);
                //ConnectionInfo connectionInfo = new PrivateKeyConnectionInfo(strPuppetServerIP, strPuppetServerName, keyFile);

                var connectionInfo = new ConnectionInfo(strPuppetServerIP, 22, strPuppetServerName, methods.ToArray());

                using (SshClient client = new SshClient(connectionInfo))
                {
                    if (!client.IsConnected)
                        client.Connect();

                    if (client.IsConnected)
                    {
                        IDictionary<Renci.SshNet.Common.TerminalModes, uint> termkvp = new Dictionary<Renci.SshNet.Common.TerminalModes, uint>();
                        termkvp.Add(Renci.SshNet.Common.TerminalModes.ECHO, 53);

                        ShellStream shellStream = client.CreateShellStream("xterm", 80, 24, 800, 600, 1024, termkvp);

                        //string strRegex = "(\\[USER@\\S*\\s*\\S*\\]$)";
                        string strRegex = "(\\[USER@\\S*\\s*~\\][#|$])";
                        //string strRegex = "([\\s*\\S*]*\\[USER@\\S*\\s*\\S*\\]#)";
                        strRegex = strRegex.Replace("USER", strPuppetServerName);

                        result = shellStream.Expect(new Regex(@strRegex)); //expect user prompt 

                        //send command
                        shellStream.WriteLine(strCmd);
                        shellStream.Flush();
                        result = shellStream.Expect(new Regex(@strRegex)); //expect user prompt
                        result = result.Replace("<", "'<'");

                        //string strCmdConfigMySQL = "sudo sed -i -e 's/\\(bind-address = \\).*/\\$(VARIABLE)/‘ /etc/my.cnf.d/server.cnf";
                        //string strCmdConfigMySQL = "sudo sed -i -e 's/\\(bind-address = \\).*/\\$(VARIABLE)/'  /etc/my.cnf.d/server.cnf";

                        //strCmdConfigMySQL = strCmdConfigMySQL.Replace("$(VARIABLE)", "1172.31.41.128");
                        //shellStream.WriteLine(strCmdConfigMySQL);

EnterpriseDataPipeline/Views/Module/Index.cshtml
@using System.Dynamic;
@using EnterpriseDataPipeline.Models;
@using System.Web.UI.WebControls;
@*@model IEnumerable<EnterpriseDataPipeline.Models.ModuleTB>*@

@model EnterpriseDataPipeline.ViewModel.ViewModelModuleVM

@{
    ViewBag.Title = "SV4U Enterprise Data PipeLine - Module Installation";
}


<script>

    $(document).ready(function () {
        $("body").css("background-color", "#F3F3F3")

        //$("select").removeAttr("multiple");

        //debugger;   //Added by Anthony Lai to debug javascript; must be removed after debug is done

        $("#btRunInstallation").bind("click", function () {

            //debugger;

            //$("#lbDestinationTableError").css('visibility', 'hidden');
            $("#taInstallationResult").empty();
            var moduleSel = $("#lbModule").val();
            var strModuleSel = "";
            if (moduleSel != null)
            {
                //var str = moduleSel.split(',');
                for (var i = 0; i < moduleSel.length; i++)
                {
                    strModuleSel += moduleSel[i] + ",";
                }
            }

            var url = "@Url.Action("RunInstallation", "Module")";
            $.get(url, {
                    module: strModuleSel,
                    destinationServerIP: $("#ddlDestinationServerIP").val()
                },
                function (data) {

                    //debugger;

                    if (data.success)
                    {
                        $("#taInstallationResult").append(data.val);

                        //var textCol = "<tr>";
                        //var colName = data.val[data.val.length - 1];
                        //for (var k = 0; k < colName.length; k++) {
                        //    textCol = textCol + "<th class='tableHeader' style='width:auto;'>" + colName[k] + "</th>";
                        //}
                        //textCol = textCol + "</tr>";
                        //$("#tblSourceQueryResult").append(textCol);

                        //var text = "";
                        //for (var i = 0; i < data.val.length-1; i++) {
                        //    //debugger;
                        //    text = text + "<tr>";
                        //    var myData = data.val[i];
                        //    for (var j = 0; j < myData.length; j++) {
                        //        text = text + "<td class='tableCell' style='width:auto; white-space:nowrap; text-overflow: ellipsis; overflow: hidden;'>" + myData[j] + "</td>";
                        //    }
                        //    text = text + "</tr>"
                        //}

                        //$("#tblSourceQueryResult").append(text);
                    }
                    else
                    {
                        //$("#lbSourceTableError").html(data.val);
                        //$("#lbSourceTableError").css('visibility', 'visible');
                        //$("#lbSourceTableError").css('color', 'red');
                    }
                });
        });

    });

</script>


<h2>
    @ViewBag.Title.
</h2>

<div class="row">
    <div class="col-md-8">   
            <h4>Select module to perform installation.</h4>
            <br />
            @*Source Query*@
            <table align="left" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
                <tbody>
                    <tr>
                        <td style="width: 20%; text-align: center;">
                            <label>Module:</label>
                        </td>
                        <td style="width: 20%; text-align: center;">
                            <label>Destination Server IP</label>
                        </td>
                        <td style="width: 20%; text-align: center;">
                            <label>Action</label>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            @if (Model != null)
                            {
                                @Html.ListBox("Module", new SelectList(Model.allModuleTB.Select(i => i.Name).Distinct().ToList(), "Mysql"), new { @class = "width305", @id = "lbModule", size = 5, style = "height: 180px; width:auto;" })
                            }
                        </td>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            @*@{var mItemsTB = new List<SelectListItem> {
                                    new SelectListItem { Text = "198.89.115.49", Value = "198.89.115.49"},
                                    new SelectListItem { Text = "198.89.115.123", Value = "198.89.115.123"} };}
                            @Html.DropDownList("DestinationServerIP", new SelectList(mItemsTB, "Value", "Text", mItemsTB.ToString()), new { @class = "width305", @id = "ddlDestinationServerIP", size = 1, style = "width:auto" })*@
                            @if (Model != null)
                            {
                                @Html.DropDownList("DestinationServerIP", new SelectList(Model.allModuleServer.Select(i => i.IPAddress).Distinct().ToList(), "198.89.115.123"), new { @class = "width305", @id = "ddlDestinationServerIP", size = 1, style = "width:auto" })
                            }
                        </td>
                        <td style="width: 20%; text-align: center;" valign="middle">
                            <input id="btRunInstallation" type="submit" value="Run Installation" class="btn btn-default" />
                        </td>
                    </tr>
                </tbody>
            </table>  
            <br />
            <br />      
        </div>
</div>

<div>
    <table align="left" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
        <tbody>
            <tr>
                <td>
                    <label>Installation Result:</label>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextArea("InstallationResult", null, new { @class = "form-control-SV4U-TextArea", @id = "taInstallationResult", @cols = "250", @style = "height: 200px; width: 600px;" })
                </td>
            </tr>
        </tbody>
    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseDataPipeline/Views/Module/RunJob.cshtml
@using EnterpriseDataPipeline.Models
@using System.Web.UI.WebControls; 
@model IEnumerable<object[]>
@{
    ViewBag.Title = "SV4U Enterprise Data PipeLine";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Index", "Job", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {

                <h4>Select a job to run.</h4>
                <hr />                
                <table align="center" class="taskList" bordercolor="#bbbbbb" style="width: 600px; border-collapse: collapse;" border="1" cellspacing="0" cellpadding="3">
				<tbody>
					<tr>
						<td style="width: 20%; text-align: center;">
							<label>Source</label>
						</td>
						<td style="width: 20%; text-align: center;">
							<label>Action</label>
						</td>						
						<td style="width: 20%; text-align: center;">
							<label>Destination</label>
						</td>						
					</tr>
					<tr>
						<td style="width: 20%; text-align: center;">
							<div class="form-group">								
                                    @{var source = new List<ListItem>
									    {
										      new ListItem { Text = "HDFS", Value="HDFS" },
										      new ListItem { Text = "Hive", Value="Hive" },
										      new ListItem { Text = "MySQL", Value="MySQL" },
										      new ListItem { Text = "Oracle", Value="Oracle" },
										      new ListItem { Text = "AWS", Value="AWS" },
										      new ListItem { Text = "MogoDB", Value="MogoDB" }
									    };
                                    }
                                    @Html.DropDownList("MySQL", new SelectList(source, "Value", "Text"), "Please Select Source")
									
							</div> 
						</td>
						<td style="width: 20%; text-align: center;">
							<input type="submit" value="Transfer >>" class="btn btn-default" />
						</td>					
						<td style="width: 20%; text-align: center;">
							<div class="form-group">								
								@{var listItemsHDFS = new List<ListItem>
									{
										  new ListItem { Text = "HDFS", Value="HDFS" },
										  new ListItem { Text = "Hive", Value="Hive" },
										  new ListItem { Text = "MySQL", Value="MySQL" },
										  new ListItem { Text = "Oracle", Value="Oracle" },
										  new ListItem { Text = "AWS", Value="AWS" },
										  new ListItem { Text = "MogoDB", Value="MogoDB" }
									};
								}
								@Html.DropDownList("HDFS",new SelectList(listItemsHDFS,"Value","Text"))
							</div>	
						</td>
					</tr>
				  </tbody>
				</table>             
            }

        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}